apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: web
  ports:
    - port: {{ .Values.service.port }}
      #targetPort: http
      targetPort: 3000
      #protocol: TCP
      #name: http
  
